lang: generic
script:
- make
env:
  global:
  - secure: apSu0zNqavGTA2lXEOUJWKiGgQ8KYwWnvIwfZ3Ev8IA4XfnCrondbADCE/hbZDp01ajGx5wDXLy8FZhlz5OrKGIVryMW2jSbSriRERUWxVBvm8SQuA2sTOdaQLA+KbjsdUzs8Mh3wPFFFvLqpQO14PnkPvS565IQZvNnEzO9kaUapgphLf38znn6TzrYDzrXotf4iBxe/1O+C61KrdKVLi0I3CkQkz86Vc+1aXcbvMEdt63NVNBsXryJw6yM9s+PPg4PeqqD34znqFMbX3Unw7YZXnOX3U3uIcLWdyAZX9RD8y8IH2Pkr0EGusy1301OCx3J+dH27OVuAD6n1nYjgNlFn2EvVZQ9z/E8SrxZrHKtbj0aE3TBTJHnM1Af/tr6NzoCgfX1fqqzTShZMyQhQCcYwhkPjRLQ6aDtLM5nktbK9+kcG7STwpJSM9G8bK0ahQn+MsqlEappMXRK6n/2lzBctlDQw42IbDlRGAtsOC8R5vBltM2RXHU57BlUqk6BuXAKZ8TACeRnspYw8GBuM3w/nY4NeqotWKA4cqw3DiEeTigU4iuW4GwZLXkXYctpazRlxisD8qXd+KXYHTEIkXSTzfmKv0oCmWMrOpW+Hq0DHnWsiWvryjvPM0bwje6848j7IuEWnsuLi1x7OTEIq4AbAETOtkqz5l6jzKX3ygA=
